osx_image: xcode7.1
language: objective-c
before_install:
  - brew update
  - brew install carthage
install: true
script: Scripts/cibuild
deploy:
  provider: releases
  api_key:
    secure: L/cNyt66n6D2CxGAN4QZxr/G29U1DD6MTGykB4MBfh7jnZcFVODN3pyuVGIcJ6d8mnfhPCcYar+y3LoyUHMFZMRRTr+gfji8rzG4xO1imTlg2iUS6JoLlqJYkGtU5iZJgISMpHovTwcejLAFIqDcZd/sKcdbV8ONQ8bzQ8ef07VftFGl+vzjgoGRMLYh2jW7bRYWPLX2Cd5EBwGZEm8xdzRN2TUOqTExtLr49OVOY4ZoI/C0MM5SLvFrYUuMwZ/702AQRrp6KfdCXE+vQbNvdSjEwrqcwTtUOgm8SZgL24/23BzbVhNUZ2xBTnc+xz5OrrG3CZAMrfxaHFVJdxMHS/yCovhnpOhY3mv8EjnAKmkkp1ClpPe5Lyc97rER1VMNjol0x4pIMkrue3xaary5LWfpbWorxR4P+Hi73A5vSmXO+9KF0DLs06i2Io3hdc3Bnb7xAE7agxzGqbvWrXLULAC1HY++H5QKEsWTpELRq1ZxYw8QT80dWCqnbjP0jkHEwOcwx8zY7AZWySPdOwdteb93DjzJ2ZEkdo9bpvhkZpxmHvo8CwlqVtc1SQrYl0DU+O+AJp8gwxhvrqEYBJqXKkWP0enMHMD/7PvggJIA/m4lJl87JtLIUiksFLoSdsnq6+OmDFcN53x+nIqD3tbX5nGhDosdKijEeeCSXFNrAcw=
  file: Platinum.framework.zip
  on:
    tags: true
